# The host to query when running healthchecks on apps
server: localhost

# Details repositories to be downloaded, bootstrapped, and executed.
apps:
  -
    name: api
    repo: digitalmarketplace-api
    short-name: api
    bootstrap: make requirements-dev run-migrations
    run-order: 1
    healthcheck:
      port: 5000
      endpoint: /_status
    commands:
      run: make run-app
      rebuild: make run-all

  -
    name: search-api
    repo: digitalmarketplace-search-api
    short-name: search
    bootstrap: make requirements-dev
    run-order: 1
    healthcheck:
      port: 5001
      endpoint: /_status
    commands:
      run: make run-app
      rebuild: make run-all

  -
    name: admin-frontend
    repo: digitalmarketplace-admin-frontend
    short-name: admin
    bootstrap: make requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5004
      endpoint: /admin/_status
    commands:
      run: make run-app
      rebuild: make run-all
      frontend: make frontend-build

  -
    name: brief-responses-frontend
    repo: digitalmarketplace-brief-responses-frontend
    short-name: brf-resp
    bootstrap: make requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5006
      endpoint: /suppliers/opportunities/_status
    commands:
      run: make run-app
      rebuild: make run-all
      frontend: make frontend-build

  -
    name: briefs-frontend
    repo: digitalmarketplace-briefs-frontend
    short-name: briefs
    bootstrap: make requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5005
      endpoint: /buyers/_status
    commands:
      run: make run-app
      rebuild: make run-all
      frontend: make frontend-build

  -
    name: buyer-frontend
    repo: digitalmarketplace-buyer-frontend
    short-name: buyer
    bootstrap: make requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5002
      endpoint: /_status
    commands:
      run: make run-app
      rebuild: make run-all
      frontend: make frontend-build

  -
    name: supplier-frontend
    repo: digitalmarketplace-supplier-frontend
    short-name: supplier
    bootstrap: make requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5003
      endpoint: /suppliers/_status
    commands:
      run: make run-app
      rebuild: make run-all
      frontend: make frontend-build

  -
    name: user-frontend
    repo: digitalmarketplace-user-frontend
    short-name: user
    bootstrap: make requirements-dev frontend-build
    run-order: 2
    healthcheck:
      port: 5007
      endpoint: /user/_status
    commands:
      run: make run-app
      rebuild: make run-all
      frontend: make frontend-build

  # Additional repositories to download and bootstrap during setup, but aren't "run" like the rest of the apps.
  -
    name: scripts
    repo: digitalmarketplace-scripts
    bootstrap: make requirements-dev

  -
    name: functional-tests
    repo: digitalmarketplace-functional-tests

index:
  repository: digitalmarketplace-scripts
  command: venv/bin/python scripts/index-to-search-service.py
  test: http://localhost:9200/{index}

  dependencies:
    - digitalmarketplace-api
    - digitalmarketplace-search-api

  indices:
    - positional:
        - services
        - dev
      keyword:
        frameworks: g-cloud-11
        index: g-cloud-11
        create-with-mapping: services-g-cloud-11

    - positional:
        - briefs
        - dev
      keyword:
        frameworks: digital-outcomes-and-specialists-3
        index: briefs-digital-outcomes-and-specialists
        create-with-mapping: briefs-digital-outcomes-and-specialists-2
