version: '3.5'

networks:
  dmrunner:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  postgres:
    container_name: dm-postgres
    networks:
      - dmrunner
    image: "postgres@sha256:f4603c7b8aaf418393edb8cd5e2d1abd91d686ab571302dc83f887ea4a56286b"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: $USER
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgresql://$${POSTGRES_USER:-postgres}@localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    container_name: dm-elasticsearch
    networks:
      - dmrunner
    image: "elasticsearch:5.4"
    ports:
      - "9200:9200"

  nginx:
    container_name: dm-nginx
    networks:
      - dmrunner
    image: "digitalmarketplace/dmrunner-nginx"
    build:
      context: ./
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"

