version: '2'

networks:
  dmrunner:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  postgres:
    container_name: dm-postgres
    networks:
      - dmrunner
    image: "postgres@sha256:888b62ebb1265a7df59258fa22227e707faa2b39d9abfe2a1d6f9e3cd5936468"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - DMRUNNER_USER

  elasticsearch:
    container_name: dm-elasticsearch
    networks:
      - dmrunner
    image: "elasticsearch:5.4"
    ports:
      - "9200:9200"

  nginx:
    container_name: dm-nginx
    networks:
      - dmrunner
    image: "digitalmarketplace/dmrunner-nginx"
    build:
      context: ./
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"

