version: '3.5'

services:
  postgres:
    image: "postgres@sha256:f4603c7b8aaf418393edb8cd5e2d1abd91d686ab571302dc83f887ea4a56286b"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: $USER
    healthcheck:
      test: "pg_isready --host=localhost --user=$${POSTGRES_USER:-postgres} || exit 1"
      interval: 30s
      start_period: 2m

  elasticsearch:
    image: "elasticsearch:5.6"
    ports:
      - "9200:9200"

  nginx:
    image: "nginx:1.14-alpine"
    ports:
      - "80:80"
    volumes:
      - "./dmrunner-nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
